/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RentALabRouteImport } from './routes/rent-a-lab'
import { Route as RdPortfolioRouteImport } from './routes/rd-portfolio'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IpPublicationsRouteImport } from './routes/ip-publications'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as Covid19RouteImport } from './routes/covid-19'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as EditorIndexRouteImport } from './routes/editor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopWishlistRouteImport } from './routes/shop.wishlist'
import { Route as ShopTrackRouteImport } from './routes/shop.track'
import { Route as ShopSearchRouteImport } from './routes/shop.search'
import { Route as ShopDealsRouteImport } from './routes/shop.deals'
import { Route as ShopCheckoutRouteImport } from './routes/shop.checkout'
import { Route as ShopCategoriesRouteImport } from './routes/shop.categories'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopAccountRouteImport } from './routes/shop.account'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as EditorShopRouteImport } from './routes/editor.shop'
import { Route as EditorProfileRouteImport } from './routes/editor.profile'
import { Route as EditorOrdersRouteImport } from './routes/editor.orders'
import { Route as EditorNewsRouteImport } from './routes/editor.news'
import { Route as EditorMediaRouteImport } from './routes/editor.media'
import { Route as EditorGalleryRouteImport } from './routes/editor.gallery'
import { Route as EditorDraftsRouteImport } from './routes/editor.drafts'
import { Route as EditorDealRouteImport } from './routes/editor.deal'
import { Route as EditorContactRouteImport } from './routes/editor.contact'
import { Route as EditorCollectionsRouteImport } from './routes/editor.collections'
import { Route as EditorAcademyRouteImport } from './routes/editor.academy'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminShopRouteImport } from './routes/admin.shop'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminDealRouteImport } from './routes/admin.deal'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAcademyRouteImport } from './routes/admin.academy'
import { Route as AcademyDashboardRouteImport } from './routes/academy.dashboard'
import { Route as AcademyCheckoutRouteImport } from './routes/academy.checkout'
import { Route as ShopSectionKeyRouteImport } from './routes/shop.section.$key'
import { Route as ShopProductIdRouteImport } from './routes/shop.product.$id'
import { Route as ShopCategorySlugRouteImport } from './routes/shop.category.$slug'
import { Route as EditorAcademyIdRouteImport } from './routes/editor.academy.$id'
import { Route as AdminAcademyIdRouteImport } from './routes/admin.academy.$id'
import { Route as AcademyReadCourseIdRouteImport } from './routes/academy.read.$courseId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RentALabRoute = RentALabRouteImport.update({
  id: '/rent-a-lab',
  path: '/rent-a-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RdPortfolioRoute = RdPortfolioRouteImport.update({
  id: '/rd-portfolio',
  path: '/rd-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IpPublicationsRoute = IpPublicationsRouteImport.update({
  id: '/ip-publications',
  path: '/ip-publications',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const Covid19Route = Covid19RouteImport.update({
  id: '/covid-19',
  path: '/covid-19',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopWishlistRoute = ShopWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTrackRoute = ShopTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ShopDealsRoute = ShopDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategoriesRoute = ShopCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const EditorShopRoute = EditorShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => EditorRoute,
} as any)
const EditorProfileRoute = EditorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EditorRoute,
} as any)
const EditorOrdersRoute = EditorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => EditorRoute,
} as any)
const EditorNewsRoute = EditorNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => EditorRoute,
} as any)
const EditorMediaRoute = EditorMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => EditorRoute,
} as any)
const EditorGalleryRoute = EditorGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => EditorRoute,
} as any)
const EditorDraftsRoute = EditorDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => EditorRoute,
} as any)
const EditorDealRoute = EditorDealRouteImport.update({
  id: '/deal',
  path: '/deal',
  getParentRoute: () => EditorRoute,
} as any)
const EditorContactRoute = EditorContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EditorRoute,
} as any)
const EditorCollectionsRoute = EditorCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => EditorRoute,
} as any)
const EditorAcademyRoute = EditorAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => EditorRoute,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealRoute = AdminDealRouteImport.update({
  id: '/deal',
  path: '/deal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademyRoute = AdminAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AdminRoute,
} as any)
const AcademyDashboardRoute = AcademyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCheckoutRoute = AcademyCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AcademyRoute,
} as any)
const ShopSectionKeyRoute = ShopSectionKeyRouteImport.update({
  id: '/section/$key',
  path: '/section/$key',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategorySlugRoute = ShopCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const EditorAcademyIdRoute = EditorAcademyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EditorAcademyRoute,
} as any)
const AdminAcademyIdRoute = AdminAcademyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAcademyRoute,
} as any)
const AcademyReadCourseIdRoute = AcademyReadCourseIdRouteImport.update({
  id: '/read/$courseId',
  path: '/read/$courseId',
  getParentRoute: () => AcademyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/covid-19': typeof Covid19Route
  '/editor': typeof EditorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/ip-publications': typeof IpPublicationsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/rd-portfolio': typeof RdPortfolioRoute
  '/rent-a-lab': typeof RentALabRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/academy/checkout': typeof AcademyCheckoutRoute
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/admin/academy': typeof AdminAcademyRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/deal': typeof AdminDealRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/editor/academy': typeof EditorAcademyRouteWithChildren
  '/editor/collections': typeof EditorCollectionsRoute
  '/editor/contact': typeof EditorContactRoute
  '/editor/deal': typeof EditorDealRoute
  '/editor/drafts': typeof EditorDraftsRoute
  '/editor/gallery': typeof EditorGalleryRoute
  '/editor/media': typeof EditorMediaRoute
  '/editor/news': typeof EditorNewsRoute
  '/editor/orders': typeof EditorOrdersRoute
  '/editor/profile': typeof EditorProfileRoute
  '/editor/shop': typeof EditorShopRoute
  '/news/$slug': typeof NewsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/deals': typeof ShopDealsRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/track': typeof ShopTrackRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/academy/read/$courseId': typeof AcademyReadCourseIdRoute
  '/admin/academy/$id': typeof AdminAcademyIdRoute
  '/editor/academy/$id': typeof EditorAcademyIdRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/shop/section/$key': typeof ShopSectionKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/careers': typeof CareersRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/covid-19': typeof Covid19Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/ip-publications': typeof IpPublicationsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/rd-portfolio': typeof RdPortfolioRoute
  '/rent-a-lab': typeof RentALabRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/academy/checkout': typeof AcademyCheckoutRoute
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/admin/academy': typeof AdminAcademyRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/deal': typeof AdminDealRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/editor/academy': typeof EditorAcademyRouteWithChildren
  '/editor/collections': typeof EditorCollectionsRoute
  '/editor/contact': typeof EditorContactRoute
  '/editor/deal': typeof EditorDealRoute
  '/editor/drafts': typeof EditorDraftsRoute
  '/editor/gallery': typeof EditorGalleryRoute
  '/editor/media': typeof EditorMediaRoute
  '/editor/news': typeof EditorNewsRoute
  '/editor/orders': typeof EditorOrdersRoute
  '/editor/profile': typeof EditorProfileRoute
  '/editor/shop': typeof EditorShopRoute
  '/news/$slug': typeof NewsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/deals': typeof ShopDealsRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/track': typeof ShopTrackRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/admin': typeof AdminIndexRoute
  '/editor': typeof EditorIndexRoute
  '/shop': typeof ShopIndexRoute
  '/academy/read/$courseId': typeof AcademyReadCourseIdRoute
  '/admin/academy/$id': typeof AdminAcademyIdRoute
  '/editor/academy/$id': typeof EditorAcademyIdRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/shop/section/$key': typeof ShopSectionKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/covid-19': typeof Covid19Route
  '/editor': typeof EditorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/ip-publications': typeof IpPublicationsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/rd-portfolio': typeof RdPortfolioRoute
  '/rent-a-lab': typeof RentALabRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/academy/checkout': typeof AcademyCheckoutRoute
  '/academy/dashboard': typeof AcademyDashboardRoute
  '/admin/academy': typeof AdminAcademyRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/deal': typeof AdminDealRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/editor/academy': typeof EditorAcademyRouteWithChildren
  '/editor/collections': typeof EditorCollectionsRoute
  '/editor/contact': typeof EditorContactRoute
  '/editor/deal': typeof EditorDealRoute
  '/editor/drafts': typeof EditorDraftsRoute
  '/editor/gallery': typeof EditorGalleryRoute
  '/editor/media': typeof EditorMediaRoute
  '/editor/news': typeof EditorNewsRoute
  '/editor/orders': typeof EditorOrdersRoute
  '/editor/profile': typeof EditorProfileRoute
  '/editor/shop': typeof EditorShopRoute
  '/news/$slug': typeof NewsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/categories': typeof ShopCategoriesRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/deals': typeof ShopDealsRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/track': typeof ShopTrackRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/academy/read/$courseId': typeof AcademyReadCourseIdRoute
  '/admin/academy/$id': typeof AdminAcademyIdRoute
  '/editor/academy/$id': typeof EditorAcademyIdRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/shop/section/$key': typeof ShopSectionKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/careers'
    | '/collections'
    | '/contact'
    | '/covid-19'
    | '/editor'
    | '/forgot-password'
    | '/gallery'
    | '/ip-publications'
    | '/login'
    | '/news'
    | '/rd-portfolio'
    | '/rent-a-lab'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/verify'
    | '/academy/checkout'
    | '/academy/dashboard'
    | '/admin/academy'
    | '/admin/analytics'
    | '/admin/careers'
    | '/admin/collections'
    | '/admin/contact'
    | '/admin/deal'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/users'
    | '/collections/$id'
    | '/editor/academy'
    | '/editor/collections'
    | '/editor/contact'
    | '/editor/deal'
    | '/editor/drafts'
    | '/editor/gallery'
    | '/editor/media'
    | '/editor/news'
    | '/editor/orders'
    | '/editor/profile'
    | '/editor/shop'
    | '/news/$slug'
    | '/services/$slug'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/categories'
    | '/shop/checkout'
    | '/shop/deals'
    | '/shop/search'
    | '/shop/track'
    | '/shop/wishlist'
    | '/admin/'
    | '/editor/'
    | '/shop/'
    | '/academy/read/$courseId'
    | '/admin/academy/$id'
    | '/editor/academy/$id'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/shop/section/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/careers'
    | '/collections'
    | '/contact'
    | '/covid-19'
    | '/forgot-password'
    | '/gallery'
    | '/ip-publications'
    | '/login'
    | '/news'
    | '/rd-portfolio'
    | '/rent-a-lab'
    | '/services'
    | '/sitemap.xml'
    | '/verify'
    | '/academy/checkout'
    | '/academy/dashboard'
    | '/admin/academy'
    | '/admin/analytics'
    | '/admin/careers'
    | '/admin/collections'
    | '/admin/contact'
    | '/admin/deal'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/users'
    | '/collections/$id'
    | '/editor/academy'
    | '/editor/collections'
    | '/editor/contact'
    | '/editor/deal'
    | '/editor/drafts'
    | '/editor/gallery'
    | '/editor/media'
    | '/editor/news'
    | '/editor/orders'
    | '/editor/profile'
    | '/editor/shop'
    | '/news/$slug'
    | '/services/$slug'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/categories'
    | '/shop/checkout'
    | '/shop/deals'
    | '/shop/search'
    | '/shop/track'
    | '/shop/wishlist'
    | '/admin'
    | '/editor'
    | '/shop'
    | '/academy/read/$courseId'
    | '/admin/academy/$id'
    | '/editor/academy/$id'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/shop/section/$key'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/careers'
    | '/collections'
    | '/contact'
    | '/covid-19'
    | '/editor'
    | '/forgot-password'
    | '/gallery'
    | '/ip-publications'
    | '/login'
    | '/news'
    | '/rd-portfolio'
    | '/rent-a-lab'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/verify'
    | '/academy/checkout'
    | '/academy/dashboard'
    | '/admin/academy'
    | '/admin/analytics'
    | '/admin/careers'
    | '/admin/collections'
    | '/admin/contact'
    | '/admin/deal'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/users'
    | '/collections/$id'
    | '/editor/academy'
    | '/editor/collections'
    | '/editor/contact'
    | '/editor/deal'
    | '/editor/drafts'
    | '/editor/gallery'
    | '/editor/media'
    | '/editor/news'
    | '/editor/orders'
    | '/editor/profile'
    | '/editor/shop'
    | '/news/$slug'
    | '/services/$slug'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/categories'
    | '/shop/checkout'
    | '/shop/deals'
    | '/shop/search'
    | '/shop/track'
    | '/shop/wishlist'
    | '/admin/'
    | '/editor/'
    | '/shop/'
    | '/academy/read/$courseId'
    | '/admin/academy/$id'
    | '/editor/academy/$id'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/shop/section/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  Covid19Route: typeof Covid19Route
  EditorRoute: typeof EditorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  IpPublicationsRoute: typeof IpPublicationsRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  RdPortfolioRoute: typeof RdPortfolioRoute
  RentALabRoute: typeof RentALabRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-a-lab': {
      id: '/rent-a-lab'
      path: '/rent-a-lab'
      fullPath: '/rent-a-lab'
      preLoaderRoute: typeof RentALabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rd-portfolio': {
      id: '/rd-portfolio'
      path: '/rd-portfolio'
      fullPath: '/rd-portfolio'
      preLoaderRoute: typeof RdPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-publications': {
      id: '/ip-publications'
      path: '/ip-publications'
      fullPath: '/ip-publications'
      preLoaderRoute: typeof IpPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covid-19': {
      id: '/covid-19'
      path: '/covid-19'
      fullPath: '/covid-19'
      preLoaderRoute: typeof Covid19RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/wishlist': {
      id: '/shop/wishlist'
      path: '/wishlist'
      fullPath: '/shop/wishlist'
      preLoaderRoute: typeof ShopWishlistRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/track': {
      id: '/shop/track'
      path: '/track'
      fullPath: '/shop/track'
      preLoaderRoute: typeof ShopTrackRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/deals': {
      id: '/shop/deals'
      path: '/deals'
      fullPath: '/shop/deals'
      preLoaderRoute: typeof ShopDealsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/categories': {
      id: '/shop/categories'
      path: '/categories'
      fullPath: '/shop/categories'
      preLoaderRoute: typeof ShopCategoriesRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/editor/shop': {
      id: '/editor/shop'
      path: '/shop'
      fullPath: '/editor/shop'
      preLoaderRoute: typeof EditorShopRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/profile': {
      id: '/editor/profile'
      path: '/profile'
      fullPath: '/editor/profile'
      preLoaderRoute: typeof EditorProfileRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/orders': {
      id: '/editor/orders'
      path: '/orders'
      fullPath: '/editor/orders'
      preLoaderRoute: typeof EditorOrdersRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/news': {
      id: '/editor/news'
      path: '/news'
      fullPath: '/editor/news'
      preLoaderRoute: typeof EditorNewsRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/media': {
      id: '/editor/media'
      path: '/media'
      fullPath: '/editor/media'
      preLoaderRoute: typeof EditorMediaRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/gallery': {
      id: '/editor/gallery'
      path: '/gallery'
      fullPath: '/editor/gallery'
      preLoaderRoute: typeof EditorGalleryRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/drafts': {
      id: '/editor/drafts'
      path: '/drafts'
      fullPath: '/editor/drafts'
      preLoaderRoute: typeof EditorDraftsRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/deal': {
      id: '/editor/deal'
      path: '/deal'
      fullPath: '/editor/deal'
      preLoaderRoute: typeof EditorDealRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/contact': {
      id: '/editor/contact'
      path: '/contact'
      fullPath: '/editor/contact'
      preLoaderRoute: typeof EditorContactRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/collections': {
      id: '/editor/collections'
      path: '/collections'
      fullPath: '/editor/collections'
      preLoaderRoute: typeof EditorCollectionsRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/academy': {
      id: '/editor/academy'
      path: '/academy'
      fullPath: '/editor/academy'
      preLoaderRoute: typeof EditorAcademyRouteImport
      parentRoute: typeof EditorRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deal': {
      id: '/admin/deal'
      path: '/deal'
      fullPath: '/admin/deal'
      preLoaderRoute: typeof AdminDealRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academy': {
      id: '/admin/academy'
      path: '/academy'
      fullPath: '/admin/academy'
      preLoaderRoute: typeof AdminAcademyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/academy/dashboard': {
      id: '/academy/dashboard'
      path: '/dashboard'
      fullPath: '/academy/dashboard'
      preLoaderRoute: typeof AcademyDashboardRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/checkout': {
      id: '/academy/checkout'
      path: '/checkout'
      fullPath: '/academy/checkout'
      preLoaderRoute: typeof AcademyCheckoutRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/shop/section/$key': {
      id: '/shop/section/$key'
      path: '/section/$key'
      fullPath: '/shop/section/$key'
      preLoaderRoute: typeof ShopSectionKeyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/category/$slug': {
      id: '/shop/category/$slug'
      path: '/category/$slug'
      fullPath: '/shop/category/$slug'
      preLoaderRoute: typeof ShopCategorySlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/editor/academy/$id': {
      id: '/editor/academy/$id'
      path: '/$id'
      fullPath: '/editor/academy/$id'
      preLoaderRoute: typeof EditorAcademyIdRouteImport
      parentRoute: typeof EditorAcademyRoute
    }
    '/admin/academy/$id': {
      id: '/admin/academy/$id'
      path: '/$id'
      fullPath: '/admin/academy/$id'
      preLoaderRoute: typeof AdminAcademyIdRouteImport
      parentRoute: typeof AdminAcademyRoute
    }
    '/academy/read/$courseId': {
      id: '/academy/read/$courseId'
      path: '/read/$courseId'
      fullPath: '/academy/read/$courseId'
      preLoaderRoute: typeof AcademyReadCourseIdRouteImport
      parentRoute: typeof AcademyRoute
    }
  }
}

interface AcademyRouteChildren {
  AcademyCheckoutRoute: typeof AcademyCheckoutRoute
  AcademyDashboardRoute: typeof AcademyDashboardRoute
  AcademyReadCourseIdRoute: typeof AcademyReadCourseIdRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyCheckoutRoute: AcademyCheckoutRoute,
  AcademyDashboardRoute: AcademyDashboardRoute,
  AcademyReadCourseIdRoute: AcademyReadCourseIdRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface AdminAcademyRouteChildren {
  AdminAcademyIdRoute: typeof AdminAcademyIdRoute
}

const AdminAcademyRouteChildren: AdminAcademyRouteChildren = {
  AdminAcademyIdRoute: AdminAcademyIdRoute,
}

const AdminAcademyRouteWithChildren = AdminAcademyRoute._addFileChildren(
  AdminAcademyRouteChildren,
)

interface AdminRouteChildren {
  AdminAcademyRoute: typeof AdminAcademyRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminDealRoute: typeof AdminDealRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademyRoute: AdminAcademyRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminDealRoute: AdminDealRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopRoute: AdminShopRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface EditorAcademyRouteChildren {
  EditorAcademyIdRoute: typeof EditorAcademyIdRoute
}

const EditorAcademyRouteChildren: EditorAcademyRouteChildren = {
  EditorAcademyIdRoute: EditorAcademyIdRoute,
}

const EditorAcademyRouteWithChildren = EditorAcademyRoute._addFileChildren(
  EditorAcademyRouteChildren,
)

interface EditorRouteChildren {
  EditorAcademyRoute: typeof EditorAcademyRouteWithChildren
  EditorCollectionsRoute: typeof EditorCollectionsRoute
  EditorContactRoute: typeof EditorContactRoute
  EditorDealRoute: typeof EditorDealRoute
  EditorDraftsRoute: typeof EditorDraftsRoute
  EditorGalleryRoute: typeof EditorGalleryRoute
  EditorMediaRoute: typeof EditorMediaRoute
  EditorNewsRoute: typeof EditorNewsRoute
  EditorOrdersRoute: typeof EditorOrdersRoute
  EditorProfileRoute: typeof EditorProfileRoute
  EditorShopRoute: typeof EditorShopRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorAcademyRoute: EditorAcademyRouteWithChildren,
  EditorCollectionsRoute: EditorCollectionsRoute,
  EditorContactRoute: EditorContactRoute,
  EditorDealRoute: EditorDealRoute,
  EditorDraftsRoute: EditorDraftsRoute,
  EditorGalleryRoute: EditorGalleryRoute,
  EditorMediaRoute: EditorMediaRoute,
  EditorNewsRoute: EditorNewsRoute,
  EditorOrdersRoute: EditorOrdersRoute,
  EditorProfileRoute: EditorProfileRoute,
  EditorShopRoute: EditorShopRoute,
  EditorIndexRoute: EditorIndexRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCategoriesRoute: typeof ShopCategoriesRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopDealsRoute: typeof ShopDealsRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopTrackRoute: typeof ShopTrackRoute
  ShopWishlistRoute: typeof ShopWishlistRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCategorySlugRoute: typeof ShopCategorySlugRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopSectionKeyRoute: typeof ShopSectionKeyRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCategoriesRoute: ShopCategoriesRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopDealsRoute: ShopDealsRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopTrackRoute: ShopTrackRoute,
  ShopWishlistRoute: ShopWishlistRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCategorySlugRoute: ShopCategorySlugRoute,
  ShopProductIdRoute: ShopProductIdRoute,
  ShopSectionKeyRoute: ShopSectionKeyRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  Covid19Route: Covid19Route,
  EditorRoute: EditorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  IpPublicationsRoute: IpPublicationsRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  RdPortfolioRoute: RdPortfolioRoute,
  RentALabRoute: RentALabRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
